# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detect_satsviz_dialog_base.ui'
#
# Created: Wed Jul 22 14:56:03 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(528, 416)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 511, 351))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Input = QtGui.QWidget()
        self.Input.setObjectName(_fromUtf8("Input"))
        self.label = QtGui.QLabel(self.Input)
        self.label.setGeometry(QtCore.QRect(110, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lao UI"))
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.comboBox_5 = QtGui.QComboBox(self.Input)
        self.comboBox_5.setGeometry(QtCore.QRect(230, 20, 141, 22))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.label_10 = QtGui.QLabel(self.Input)
        self.label_10.setGeometry(QtCore.QRect(60, 240, 91, 16))
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.frame_2 = QtGui.QFrame(self.Input)
        self.frame_2.setGeometry(QtCore.QRect(40, 260, 421, 51))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 71, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(230, 20, 61, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.dateEdit = QtGui.QDateEdit(self.frame_2)
        self.dateEdit.setGeometry(QtCore.QRect(100, 20, 110, 22))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.dateEdit_2 = QtGui.QDateEdit(self.frame_2)
        self.dateEdit_2.setGeometry(QtCore.QRect(290, 20, 110, 22))
        self.dateEdit_2.setObjectName(_fromUtf8("dateEdit_2"))
        self.frame = QtGui.QFrame(self.Input)
        self.frame.setGeometry(QtCore.QRect(40, 60, 421, 141))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.comboBox_4 = QtGui.QComboBox(self.frame)
        self.comboBox_4.setGeometry(QtCore.QRect(190, 100, 131, 22))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(100, 100, 91, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(100, 10, 53, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.comboBox_3 = QtGui.QComboBox(self.frame)
        self.comboBox_3.setGeometry(QtCore.QRect(190, 70, 131, 22))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(100, 40, 53, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.comboBox_2 = QtGui.QComboBox(self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(190, 40, 131, 22))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(100, 70, 81, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.comboBox = QtGui.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(190, 10, 131, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.tabWidget.addTab(self.Input, _fromUtf8(""))
        self.Analysis = QtGui.QWidget()
        self.Analysis.setObjectName(_fromUtf8("Analysis"))
        self.label_9 = QtGui.QLabel(self.Analysis)
        self.label_9.setGeometry(QtCore.QRect(110, 288, 53, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_6 = QtGui.QLabel(self.Analysis)
        self.label_6.setGeometry(QtCore.QRect(180, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lao UI"))
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setMouseTracking(False)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.frame_5 = QtGui.QFrame(self.Analysis)
        self.frame_5.setGeometry(QtCore.QRect(350, 30, 141, 101))
        self.frame_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.radioButton_15 = QtGui.QRadioButton(self.frame_5)
        self.radioButton_15.setGeometry(QtCore.QRect(10, 70, 131, 20))
        self.radioButton_15.setObjectName(_fromUtf8("radioButton_15"))
        self.radioButton_13 = QtGui.QRadioButton(self.frame_5)
        self.radioButton_13.setGeometry(QtCore.QRect(10, 10, 95, 20))
        self.radioButton_13.setObjectName(_fromUtf8("radioButton_13"))
        self.radioButton_14 = QtGui.QRadioButton(self.frame_5)
        self.radioButton_14.setGeometry(QtCore.QRect(10, 40, 95, 20))
        self.radioButton_14.setObjectName(_fromUtf8("radioButton_14"))
        self.label_7 = QtGui.QLabel(self.Analysis)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lao UI"))
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit = QtGui.QLineEdit(self.Analysis)
        self.lineEdit.setGeometry(QtCore.QRect(170, 288, 171, 22))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_8 = QtGui.QLabel(self.Analysis)
        self.label_8.setGeometry(QtCore.QRect(360, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lao UI"))
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.toolButton = QtGui.QToolButton(self.Analysis)
        self.toolButton.setGeometry(QtCore.QRect(350, 290, 27, 20))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.frame_6 = QtGui.QFrame(self.Analysis)
        self.frame_6.setGeometry(QtCore.QRect(10, 30, 331, 241))
        self.frame_6.setFrameShape(QtGui.QFrame.Box)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.comboBox_7 = QtGui.QComboBox(self.frame_6)
        self.comboBox_7.setEnabled(False)
        self.comboBox_7.setGeometry(QtCore.QRect(160, 30, 161, 22))
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_10 = QtGui.QComboBox(self.frame_6)
        self.comboBox_10.setEnabled(False)
        self.comboBox_10.setGeometry(QtCore.QRect(160, 120, 161, 22))
        self.comboBox_10.setObjectName(_fromUtf8("comboBox_10"))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.label_20 = QtGui.QLabel(self.frame_6)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 141, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.frame_6)
        self.label_21.setGeometry(QtCore.QRect(10, 160, 131, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.comboBox_13 = QtGui.QComboBox(self.frame_6)
        self.comboBox_13.setEnabled(False)
        self.comboBox_13.setGeometry(QtCore.QRect(160, 60, 161, 22))
        self.comboBox_13.setObjectName(_fromUtf8("comboBox_13"))
        self.comboBox_13.addItem(_fromUtf8(""))
        self.comboBox_13.addItem(_fromUtf8(""))
        self.comboBox_13.addItem(_fromUtf8(""))
        self.comboBox_13.addItem(_fromUtf8(""))
        self.comboBox_13.addItem(_fromUtf8(""))
        self.comboBox_13.addItem(_fromUtf8(""))
        self.comboBox_8 = QtGui.QComboBox(self.frame_6)
        self.comboBox_8.setEnabled(False)
        self.comboBox_8.setGeometry(QtCore.QRect(160, 90, 161, 22))
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_9 = QtGui.QComboBox(self.frame_6)
        self.comboBox_9.setEnabled(False)
        self.comboBox_9.setGeometry(QtCore.QRect(160, 180, 161, 22))
        self.comboBox_9.setObjectName(_fromUtf8("comboBox_9"))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_11 = QtGui.QComboBox(self.frame_6)
        self.comboBox_11.setEnabled(False)
        self.comboBox_11.setGeometry(QtCore.QRect(160, 210, 161, 22))
        self.comboBox_11.setObjectName(_fromUtf8("comboBox_11"))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.radioButton = QtGui.QRadioButton(self.frame_6)
        self.radioButton.setEnabled(True)
        self.radioButton.setGeometry(QtCore.QRect(20, 30, 121, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.frame_6)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 60, 131, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.radioButton_3 = QtGui.QRadioButton(self.frame_6)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 90, 111, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.radioButton_4 = QtGui.QRadioButton(self.frame_6)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 120, 141, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.radioButton_5 = QtGui.QRadioButton(self.frame_6)
        self.radioButton_5.setGeometry(QtCore.QRect(20, 180, 141, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.radioButton_6 = QtGui.QRadioButton(self.frame_6)
        self.radioButton_6.setGeometry(QtCore.QRect(20, 210, 111, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.tabWidget.addTab(self.Analysis, _fromUtf8(""))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setGeometry(QtCore.QRect(20, 370, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "SHAPE FILE:", None))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-style:italic; color:#000000;\">Study Period</span></p></body></html>", None))
        self.label_11.setText(_translate("Dialog", "Start Date:", None))
        self.label_12.setText(_translate("Dialog", "End Date:", None))
        self.label_5.setText(_translate("Dialog", "Location Id:", None))
        self.label_2.setText(_translate("Dialog", "Case:", None))
        self.label_3.setText(_translate("Dialog", "Control:", None))
        self.label_4.setText(_translate("Dialog", "Population:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Input), _translate("Dialog", "Input", None))
        self.label_9.setText(_translate("Dialog", "Output:", None))
        self.label_6.setText(_translate("Dialog", "Probability Model", None))
        self.radioButton_15.setText(_translate("Dialog", "High or Low Rates", None))
        self.radioButton_13.setText(_translate("Dialog", "High Rates", None))
        self.radioButton_14.setText(_translate("Dialog", "Low Rates", None))
        self.label_7.setText(_translate("Dialog", "Type Of Analysis", None))
        self.label_8.setText(_translate("Dialog", "Scan For Areas", None))
        self.toolButton.setText(_translate("Dialog", "...", None))
        self.comboBox_7.setItemText(0, _translate("Dialog", "Poisson", None))
        self.comboBox_7.setItemText(1, _translate("Dialog", "Bernoulli", None))
        self.comboBox_7.setItemText(2, _translate("Dialog", "Multinomial", None))
        self.comboBox_7.setItemText(3, _translate("Dialog", "Ordinal", None))
        self.comboBox_7.setItemText(4, _translate("Dialog", "Exponential", None))
        self.comboBox_7.setItemText(5, _translate("Dialog", "Normal", None))
        self.comboBox_10.setItemText(0, _translate("Dialog", "Poisson", None))
        self.label_20.setText(_translate("Dialog", "Retrospective Analysis:", None))
        self.label_21.setText(_translate("Dialog", "Prospective Analysis:", None))
        self.comboBox_13.setItemText(0, _translate("Dialog", "Poisson", None))
        self.comboBox_13.setItemText(1, _translate("Dialog", "Bernoulli", None))
        self.comboBox_13.setItemText(2, _translate("Dialog", "Multinomial", None))
        self.comboBox_13.setItemText(3, _translate("Dialog", "Ordinal", None))
        self.comboBox_13.setItemText(4, _translate("Dialog", "Exponential", None))
        self.comboBox_13.setItemText(5, _translate("Dialog", "Normal", None))
        self.comboBox_8.setItemText(0, _translate("Dialog", "Poisson", None))
        self.comboBox_8.setItemText(1, _translate("Dialog", "Bernoulli", None))
        self.comboBox_8.setItemText(2, _translate("Dialog", "Space-Time Permutation", None))
        self.comboBox_8.setItemText(3, _translate("Dialog", "Multinomial", None))
        self.comboBox_8.setItemText(4, _translate("Dialog", "Ordinal", None))
        self.comboBox_8.setItemText(5, _translate("Dialog", "Exponential", None))
        self.comboBox_8.setItemText(6, _translate("Dialog", "Normal", None))
        self.comboBox_9.setItemText(0, _translate("Dialog", "Poisson", None))
        self.comboBox_9.setItemText(1, _translate("Dialog", "Bernoulli", None))
        self.comboBox_9.setItemText(2, _translate("Dialog", "Multinomial", None))
        self.comboBox_9.setItemText(3, _translate("Dialog", "Ordinal", None))
        self.comboBox_9.setItemText(4, _translate("Dialog", "Exponential", None))
        self.comboBox_9.setItemText(5, _translate("Dialog", "Normal", None))
        self.comboBox_11.setItemText(0, _translate("Dialog", "Poisson", None))
        self.comboBox_11.setItemText(1, _translate("Dialog", "Bernoulli", None))
        self.comboBox_11.setItemText(2, _translate("Dialog", "Space-Time Permutation", None))
        self.comboBox_11.setItemText(3, _translate("Dialog", "Multinomial", None))
        self.comboBox_11.setItemText(4, _translate("Dialog", "Ordinal", None))
        self.comboBox_11.setItemText(5, _translate("Dialog", "Exponential", None))
        self.comboBox_11.setItemText(6, _translate("Dialog", "Normal", None))
        self.radioButton.setText(_translate("Dialog", "Purely Spatial:", None))
        self.radioButton_2.setText(_translate("Dialog", "Purely Temporal:", None))
        self.radioButton_3.setText(_translate("Dialog", "Space-Time:", None))
        self.radioButton_4.setText(_translate("Dialog", "Spatial Variation:", None))
        self.radioButton_5.setText(_translate("Dialog", "Purely Temporal:", None))
        self.radioButton_6.setText(_translate("Dialog", "Space-Time:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Analysis), _translate("Dialog", "Analysis", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

